// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjrxqeyexlusjwzzecal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqcnhxZXlleGx1c2p3enplY2FsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTMyMzAsImV4cCI6MjA2MDU2OTIzMH0.uqbiQOxbSbCr6C3LA1CkMHZ7spC5yGolK-G63JfshaY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);